import type { Metadata } from "next";
import { Inter, Princess_Sofia } from "next/font/google";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import { ToggleButton } from "@/components/toggle-button";

import "./globals.css";
import { PageHeader } from "@/components/PageHeader";
import { NavigationMenuDemo } from "@/components/NavigationMenu";
import { db } from "@/lib/db";
import TopNav from "@/components/ui/TopNav";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kayan Travel4u React App",
  description: "Generated by create next app",
};







export default  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
  
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        {children}
        <ThemeProvider

            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
      <div className="w-full h-[90px] bg-white dark:bg-black text-black dark:text-white">

      <NavigationMenuDemo />    

      <ToggleButton />


      

      

      
      </div>
        
        {children}

        {/* <div className="w-full h-[90px] bg-blue-950">Footer</div> */}

      
        </ThemeProvider>
      
      <PageHeader />
      <TopNav />
      </body>
      
      
    </html> 
  );
}
